# Establecer la imagen base
FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos requirements.txt en el contenedor
COPY requirements.txt .

# Instalar las dependencias del proyecto
RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# Copiar el resto del código de la aplicación en el contenedor
COPY . .

# Exponer el puerto en el que se ejecutará la aplicación
EXPOSE 5000
